from __future__ import annotations
import busio
import displayio
import microcontroller
import typing
"""
board Espressif ESP32-S3-DevKitC-1-N8R8
https://circuitpython.org/boards/espressif_esp32s3_devkitc_1_n8r8_hacktablet
"""
de: microcontroller.Pin = ...
vsync: microcontroller.Pin = ...
hsync: microcontroller.Pin = ...
dclk: microcontroller.Pin = ...
red: typing.Any = ...
green: typing.Any = ...
blue: typing.Any = ...
TFT_PINS: typing.Any = ...
TFT_TIMINGS: typing.Any = ...
TFT_BACKLIGHT: microcontroller.Pin = ...
IO0: microcontroller.Pin = ...
IO1: microcontroller.Pin = ...
IO2: microcontroller.Pin = ...
IO3: microcontroller.Pin = ...
TFTB1: microcontroller.Pin = ...
TFTB2: microcontroller.Pin = ...
TFTB3: microcontroller.Pin = ...
TFTB4: microcontroller.Pin = ...
TFTB5: microcontroller.Pin = ...
TFTG1: microcontroller.Pin = ...
TFTG2: microcontroller.Pin = ...
TFTG3: microcontroller.Pin = ...
TFTG4: microcontroller.Pin = ...
TFTG5: microcontroller.Pin = ...
TFTG6: microcontroller.Pin = ...
TFTR1: microcontroller.Pin = ...
TFTR2: microcontroller.Pin = ...
TFTR3: microcontroller.Pin = ...
TFTR4: microcontroller.Pin = ...
TFTR5: microcontroller.Pin = ...
IO19: microcontroller.Pin = ...
IO20: microcontroller.Pin = ...
dclk: microcontroller.Pin = ...
IO35: microcontroller.Pin = ...
IO36: microcontroller.Pin = ...
IO37: microcontroller.Pin = ...
IO38: microcontroller.Pin = ...
IO39: microcontroller.Pin = ...
TOUCH_INT: microcontroller.Pin = ...
SCL: microcontroller.Pin = ...
SDA: microcontroller.Pin = ...
IO43: microcontroller.Pin = ...
IO44: microcontroller.Pin = ...
de: microcontroller.Pin = ...
IO46: microcontroller.Pin = ...
hsync: microcontroller.Pin = ...
vsync: microcontroller.Pin = ...
NEOPIXEL: microcontroller.Pin = ...
TX: microcontroller.Pin = ...
RX: microcontroller.Pin = ...
STEMMA_I2C: typing.Any = ...
DISPLAY: displayio.Display = ...
def I2C() -> busio.I2C:
    """Returns the `busio.I2C` object for the board's designated I2C bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.I2C`.
    """
    ...


def UART() -> busio.UART:
    """Returns the `busio.UART` object for the board's designated UART bus(es).
    The object created is a singleton, and uses the default parameter values for `busio.UART`.
    """
    ...

